services:
  # База данных PostgreSQL
  database:
    image: postgres:15
    container_name: inventory_db
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Strapi Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: inventory_backend
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=postgres
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/inventory_db
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_NAME=inventory_db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - JWT_SECRET=your_super_secret_jwt_key_here
      - ADMIN_JWT_SECRET=your_admin_jwt_secret_here
      - APP_KEYS=key1,key2,key3,key4
      - API_TOKEN_SALT=your_api_token_salt_here
      - TRANSFER_TOKEN_SALT=your_transfer_token_salt_here
      - HOST=0.0.0.0
      - PORT=1337
    ports:
      - "1337:1337"
    depends_on:
      - database
    volumes:
      - ./backend/public/uploads:/app/public/uploads
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: inventory_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: